In [2]:
import numpy as np

def qr_algorithm(A, max_iterations=100, tolerance=1e-10):
    # Make a copy of the input matrix
    A_k = np.copy(A).astype(float)
    n = A.shape[0]
    
    print("Initial matrix A_0:")
    print(A_k)
    print("\n")
    
    for k in range(max_iterations):
        # Manual QR decomposition using modified Gram-Schmidt
        Q = np.zeros((n, n))
        R = np.zeros((n, n))
        
        # Extract columns of A_k
        for j in range(n):
            v = A_k[:, j].copy()
            
            # Orthogonalize against previous columns
            for i in range(j):
                R[i, j] = Q[:, i].dot(A_k[:, j])
                v = v - R[i, j] * Q[:, i]
            
            # Normalize
            R[j, j] = np.linalg.norm(v)
            if R[j, j] > tolerance:  # Avoid division by zero
                Q[:, j] = v / R[j, j]
            else:
                Q[:, j] = v
        
        # Compute A_{k+1} = R*Q
        A_next = np.dot(R, Q)
        
        print(f"Iteration {k+1}:")
        print(f"Q matrix:")
        print(Q)
        print(f"R matrix:")
        print(R)
        print(f"A_{k+1} matrix:")
        print(A_next)
        print("\n")
        
        # Check convergence: look at the sum of absolute values of off-diagonal elements
        off_diag_sum = np.sum(np.abs(np.triu(A_next, 1))) + np.sum(np.abs(np.tril(A_next, -1)))
        
        # Update A_k for next iteration
        A_k = A_next
        
        # Check if matrix is approximately upper triangular
        if off_diag_sum < tolerance:
            print(f"Converged after {k+1} iterations!")
            break
    
    # Extract eigenvalues from the diagonal
    eigenvalues = np.diag(A_k)
    
    return eigenvalues, k+1


# Insert your matrix here
A = np.array([
    [4, 1, 1, 4],
    [1, 3, -1, 4],
    [1, -1, 3, 5],
    [4, 4, 5, 2]
])

print("Running QR algorithm on matrix:")
print(A)
print("\n")

eigenvalues, iterations = qr_algorithm(A)

print(f"\nFinal approximation of eigenvalues after {iterations} iterations:")
print(eigenvalues)

# Verify with numpy's eigenvalue function
true_eigenvalues = np.linalg.eigvals(A)
print("\nTrue eigenvalues from numpy:")
print(true_eigenvalues)

# Compare results
print("\nDifference:")
# Sort both sets of eigenvalues for comparison
sorted_approx = np.sort(eigenvalues)
sorted_true = np.sort(true_eigenvalues)
print(np.abs(sorted_approx - sorted_true))

Running QR algorithm on matrix:
[[ 4  1  1  4]
 [ 1  3 -1  4]
 [ 1 -1  3  5]
 [ 4  4  5  2]]


Initial matrix A_0:
[[ 4.  1.  1.  4.]
 [ 1.  3. -1.  4.]
 [ 1. -1.  3.  5.]
 [ 4.  4.  5.  2.]]


Iteration 1:
Q matrix:
[[ 0.68599434 -0.44453856 -0.5739968  -0.04821727]
 [ 0.17149859  0.65857564 -0.358748    0.63887889]
 [ 0.17149859 -0.46100295  0.5022472   0.7112048 ]
 [ 0.68599434  0.39514539  0.538122   -0.28930365]]
R matrix:
[[ 5.83095189  3.77296887  4.45896321  5.65945331]
 [ 0.          3.57277286 -0.51039612 -0.65857564]
 [ 0.          0.          3.98210282 -0.1434992 ]
 [ 0.          0.          0.          5.34006314]]
A_1 matrix:
[[ 9.29411765  0.07341411  0.58448536  3.66325309]
 [ 0.07341411  2.32800217 -1.89246419  2.11010131]
 [ 0.58448536 -1.89246419  1.92277992  2.87360547]
 [ 3.66325309  2.11010131  2.87360547 -1.54489974]]


Iteration 2:
Q matrix:
[[ 0.92872913 -0.17275162 -0.32675497 -0.02915956]
 [ 0.00733602  0.64662566 -0.38003222  0.66135993]
 [ 0.05840561 -0.53